SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/Plz_Metadata_Status__c.object-meta.xml
<CustomObject>
    <label>Metadata Status</label>
    <nameField>
        <label>Metadata Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_flag__c.field-meta.xml
<CustomField>
    <fullName>Plz_flag__c</fullName>
    <formula>IF( ISPICKVAL( Plz_Status__c , &apos;Synchronized&apos;) , &apos;success&apos;,
IF( ISPICKVAL( Plz_Status__c , &apos;Not Synchronized&apos;) , &apos;error&apos;,
IF( ISPICKVAL( Plz_Status__c , &apos;Not Yet Analyzed&apos;) , &apos;warning&apos;,
&apos;&apos;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flag</label>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_Icon__c.field-meta.xml
<CustomField>
    <fullName>Plz_Icon__c</fullName>
    <formula>IF( AND(ISPICKVAL( Plz_Status__c , &apos;Synchronized&apos;) ,
(TODAY()- Plz_Last_Time_Analyzed__c)&gt;3 ),&apos;utility:warning&apos;,
IF( ISPICKVAL( Plz_Status__c , &apos;Not Synchronized&apos;) , &apos;utility:priority&apos;,
IF( ISPICKVAL( Plz_Status__c , &apos;Not Yet Analyzed&apos;) , &apos;utility:lower_flag&apos;,
&apos;utility:success&apos;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Icon</label>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_Last_Time_Analyzed__c.field-meta.xml
<CustomField>
    <fullName>Plz_Last_Time_Analyzed__c</fullName>
    <label>Last Time Analyzed</label>
    <type>Date</type>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_Name__c.field-meta.xml
<CustomField>
    <fullName>Plz_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_Path__c.field-meta.xml
<CustomField>
    <fullName>Plz_Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_Status__c.field-meta.xml
<CustomField>
    <fullName>Plz_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Synchronized</fullName>
            </value>
            <value>
                <fullName>Not Synchronized</fullName>
            </value>
            <value>
                <fullName>Not Yet Analyzed</fullName>
                <label>Not Analyzed Yet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SfApp/force-app/main/default/objects/Plz_Metadata_Status__c/fields/Plz_type__c.field-meta.xml
<CustomField>
    <fullName>Plz_type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MetadataStatusType</valueSetName>
    </valueSet>
</CustomField>

SfApp/force-app/main/default/objects/Queries__mdt/Queries__mdt.object-meta.xml
<CustomObject>
    <label>Queries</label>
    <pluralLabel>Queries</pluralLabel>
</CustomObject>

SfApp/force-app/main/default/objects/Queries__mdt/fields/ObjectLabel__c.field-meta.xml
<CustomField>
    <fullName>ObjectLabel__c</fullName>
    <label>Object Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/objects/Queries__mdt/fields/QueryText__c.field-meta.xml
<CustomField>
    <fullName>QueryText__c</fullName>
    <label>Query Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SfApp/force-app/main/default/classes/StatusDataTableController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-19-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class StatusDataTableController {
    @AuraEnabled( cacheable = true )
    public static List<Plz_Metadata_Status__c> fetchMedataDataStatus(String period) {
        System.debug('fetchMedataDataStatus '+period);
        Integer days = Integer.valueof(period);
        System.debug('days '+days);

        date d = system.today().addDays(-days);
        System.debug('-----d '+d);

        return [ SELECT Id, Plz_Name__c, toLabel(Plz_type__c) type, Plz_type__c, Plz_Status__c, Plz_Path__c, Plz_Last_Time_Analyzed__c, Plz_flag__c, Plz_Icon__c
                   FROM Plz_Metadata_Status__c
                   WHERE Plz_Last_Time_Analyzed__c >=: d
                   WITH SECURITY_ENFORCED ];
         
    }
    @AuraEnabled( cacheable = true )
    public static List<Queries__mdt> fetchQueriesMdt() {
     
        return [ SELECT Id, ObjectLabel__c, ObjectName__c, QueryText__c
                   FROM Queries__mdt
                   WITH SECURITY_ENFORCED];
         
    }
    
}